language: nodejs

node_js:
  - "stable"

jdk:
  - oraclejdk8

addons:
  sonarcloud: true

  
script:
  - npm run setup
  - npm run build
  - npm run test
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=lokatronao-github -Dsonar.projectKey=3732e5151898b2ca8e3d0cf767a9f3b2 -Dsonar.sources='./dist' -X