language: nodejs

node_js: 
 - "6"

jdk:
  - oraclejdk8

addons:
  sonarcloud: true

master:
  - nvm install 8
  - npm run setup
  - npm run build
  - node -v
  - nohup node dist/index.js &
  - npm run test
  - npm run cover
  - ls -l
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=lokatronao-github -Dsonar.projectKey=3732e5151898b2ca8e3d0cf767a9f3b2 -Dsonar.sources='./dist' -X
