language: nodejs

node_js: 
 - "6"

jdk:
  - oraclejdk8

addons:
  sonarcloud: true

script:
  - sudo apt-get install nodejs
  - npm run setup
  - node -v
  - npm run build
  - npm run test
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=lokatronao-github -Dsonar.projectKey=3732e5151898b2ca8e3d0cf767a9f3b2 -Dsonar.sources='./dist' -X